### ISSUE TITLE
Baking cache issue.

### ISSUE THREAD

**Issue by OmidGhotbi** [PavelBlend/Blender-Molecular-Script#14]
Baking the cache can cause error and process never will end after and continue working in background casing render issue and instability, 
Python: Traceback (most recent call last):
  File "\molecular\ops.py", line 429, in modal
    fake_context = context.copy()
  File "\blender-4.0.2\4.0\scripts\modules\bpy_types.py", line 94, in copy
    value = getattr(self, attr)
AttributeError: 'Context' object has no attribute 'grease_pencil'

**Comment by PavelBlend** [comment]
I haven't tested the addon in blender 4. Blender 4.0 and higher does not start for me:
![1](https://private-user-images.githubusercontent.com/7983249/283210470-c1a677f9-d434-4fd0-879a-22441d0ae95c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxMjQ4OTEsIm5iZiI6MTcxMzEyNDU5MSwicGF0aCI6Ii83OTgzMjQ5LzI4MzIxMDQ3MC1jMWE2NzdmOS1kNDM0LTRmZDAtODc5YS0yMjQ0MWQwYWU5NWMuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTRUMTk1NjMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGE2NDU0OWJmYzMyM2E2NjhkYjc4OGFkZGVkY2YyMTkwMmY3ZjMxMDNlOGFkMGNhZGIzZWI5MzUyY2EwMWQxMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ZCD58Tru3sn9TIa8CwUwqRkMTR8DDIyrpQN4Y-uzAvo)

Most likely the Python API changed in 4.0+, which is why the addon stopped working. I haven't encountered such an error in blender 3.6. Try using 3.6. I can't fix bugs for 4.0.

**Comment by OmidGhotbi** [comment]
Thank you i will check and patch it.
